workflows:
  ios-native-workflow:
    name: iOS Native workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: MiBAppStoreConnect
    environment:
      groups:
        - firebase_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: MiB-Flutter-CodeMagic
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_APPLE_ID: 6741551558
      xcode: latest
      cocoapods: default
    scripts:
      - name: Write Google credentials
        script: | 
          echo $FIREBASE_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
      - name: Publish to Firebase Hosting
        script: | 
          firebase deploy --token "$FIREBASE_TOKEN"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - mark.bonsor@gmail.com
        notify:
          success: true
          failure: false
      #app_store_connect:
      #  auth: integration
      #  submit_to_app_store: false
